package wrh;

import java.util.ArrayList;
import java.util.Date;
import java.text.SimpleDateFormat;

public class MessageMaker {
	
	public static String makeMessageBody(ArrayList<Match> matches) {
		/* make message body... */
		Date date = new Date(System.currentTimeMillis());
		SimpleDateFormat formatter= new SimpleDateFormat("MM/dd");
		
		StringBuilder output = new StringBuilder();
		output.append("Hello! The featured football matches for ");
		output.append(formatter.format(date));
		output.append(" are:\n");
		
		for (Match m : matches) {
			output.append("\t");
			output.append(m.toString());
			output.append("\n");
		}
		output.append("\n");
		output.append("Matches generated by featured_football");
		
		return output.toString();
	}
	
	
	
}
